name: Dependency License Scanning

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0' # At 00:00 on Sunday

permissions:
  contents: read

jobs:
  fossa:
    name: Fossa
    runs-on: ubuntu-latest
    if: github.repository == 'akka/akka-persistence-r2dbc'
    steps:
      - name: Checkout
        # https://github.com/actions/checkout/releases
        # v4.1.1
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
        with:
          fetch-depth: 0

      - name: Cache Coursier cache
        # https://github.com/coursier/cache-action/releases
        # v6.4.4
        uses: coursier/cache-action@a0e7cd24be81bc84f0d7461e02bd1a96980553d7

      - name: Set up JDK 17
        # https://github.com/coursier/setup-action/releases
        # v1.3.4
        uses: coursier/setup-action@48280172a2c999022e42527711d6b28e4945e6f0
        with:
          jvm: temurin:1.17

      - name: FOSSA policy check
        run: |-
          curl -H 'Cache-Control: no-cache' https://raw.githubusercontent.com/fossas/fossa-cli/master/install-latest.sh | bash
          fossa analyze && fossa test
        env:
          FOSSA_API_KEY: "${{secrets.FOSSA_API_KEY}}"
